# Use a micromamba base image for better non-root support
# FROM mambaorg/micromamba:latest
FROM condaforge/miniforge3

LABEL container.base.image="condaforge/miniforge3"
LABEL software.name="dskola_base_jupyter"
LABEL software.description="General-purpose jupyter lab server"

ARG USER_UID=0
ARG USER_GID=0
ARG USER_NAME=root

# RUN echo UID $USER_UID
# RUN echo GID $USER_GID

USER root

RUN apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates \
    libglib2.0-0 libxext6 libsm6 libxrender1 \
    git mercurial subversion libz-dev \
    --reinstall build-essential

WORKDIR /app
COPY launch_jupyter.sh .
RUN chmod 755 launch_jupyter.sh

# Create the user and set their home directory
RUN groupadd -g $USER_GID "domain"
RUN useradd -m -u $USER_UID -g $USER_GID -s /bin/bash $USER_NAME

# Switch to the non-root user
USER $USER_NAME
ENV HOME=/home/$USER_NAME
ENV MAMBA_ROOT_PREFIX=$HOME/local/share/mamba

# RUN mamba shell init --shell bash --root-prefix=$MAMBA_ROOT_PREFIX
# RUN eval "$(micromamba shell hook --shell bash)
# RUN micromamba activate
# RUN micromamba install -y mamba

WORKDIR /build
COPY environment-jupyter.yml .
RUN mamba create -n jupyter -f environment-jupyter.yml -y
ENV ENV_NAME=jupyter

COPY environment-bnfo-base.yml .
RUN mamba create -n bnfo-base -f environment-bnfo-base.yml -y
RUN mamba install -y -n bnfo-base ipykernel

WORKDIR $HOME

ENTRYPOINT ["/bin/bash", "/app/launch_jupyter.sh"]

