#!/bin/bash
set -uxo pipefail
MIN_PORT=8888
MAX_PORT=8988

HOST_NAME=$(hostname -s)
# FOUND_OPEN_PORT=0

for ((PORT=MIN_PORT;PORT<=MAX_PORT;PORT++)); do
    echo $PORT
    if ! ss -tuln | grep -q ":$PORT "; then
        echo "============================================================"
        echo "Trying to launch Jupyter Lab on $HOST_NAME port $PORT"
        echo "============================================================"
        echo ""

        docker run -e HOST_NAME=$HOST_NAME -e HOST_PORT=$PORT -p $PORT:8888 dskola_jls:latest
        STATUS=$?
        echo Status: $STATUS        
        if [[ $STATUS -le 1 ]]; then
            echo Success!
            break
        fi
    fi
done

if [[ $STATUS -gt 1 ]]; then
    echo "No available ports found in range ${MIN_PORT}-${MAX_PORT}!"
fi
