#!/bin/bash
set -uxo pipefail

IMAGE_NAME=docker-scratch.artifactory01.ghdna.io/dskola_jls:latest
CID_FILE=$HOME/docker_tracking/jls_latest.cid

MIN_PORT=8888
MAX_PORT=8988

HOST_NAME=$(hostname -s)
# FOUND_OPEN_PORT=0
rm -f $CID_FILE
HAD_ERROR=0

for ((PORT=MIN_PORT;PORT<=MAX_PORT;PORT++)); do
    echo $PORT
    if ! ss -tuln | grep -q ":$PORT "; then
        echo "============================================================"
        echo "Trying to launch Jupyter Lab on $HOST_NAME port $PORT"
        echo "============================================================"
        echo ""

        docker run -it --init -u $(id -u):$(id -g) -e HOST_NAME=$HOST_NAME -e HOST_PORT=$PORT -p $PORT:8888 --mount type=bind,src=$HOME/workspace,dst=/workspace --cidfile $CID_FILE $IMAGE_NAME
        STATUS=$?
        echo "Status: $STATUS"
                
        if [[ $STATUS -le 1 ]]; then
            CONTAINER_ID=$(cat $CID_FILE)
            echo "Ran $IMAGE_NAME as $CONTAINER_ID successfully (terminated normally or by TERM signal)"
            echo "Committing $CONTAINER_ID to $IMAGE_NAME ..."
            docker commit $CONTAINER_ID $IMAGE_NAME
            # docker push $IMAGE_NAME
            docker container rm $CONTAINER_ID
            break
        elif [[ $STATUS -eq 125 ]]; then
            echo "Port $PORT in use."
        else
            echo "Received other error, aborting!"
            HAD_ERROR=1           
            break
        fi
        rm -f $CID_FILE
    fi
done

if [[ $STATUS -gt 1 ]]; then
    if [[ $HAD_ERROR -eq 0 ]]; then
        echo "No available ports found in range ${MIN_PORT}-${MAX_PORT}!"
    fi
fi
